name: Deploy Website

on:
  push:
    branches:
      - main      # Produktion
      - staging   # Test-Umgebung
  pull_request:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js (falls Tailwind Build nötig)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: |
        if [ -f "package.json" ]; then
          npm ci
        fi
        
    - name: Build CSS (Tailwind)
      run: |
        if [ -f "tailwind.config.js" ]; then
          npx tailwindcss -i src/input.css -o output.css --minify
        fi
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        # Verschiedene Domains je nach Branch
        cname: |
          ${{ github.ref == 'refs/heads/main' && 'berent.ai' || 
              github.ref == 'refs/heads/staging' && 'staging.berent.ai' || 
              format('preview-{0}.berent.ai', github.head_ref) }}
        
    - name: Comment PR with Preview URL
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const prNumber = context.payload.pull_request.number;
          const branchName = context.payload.pull_request.head.ref;
          const previewUrl = `https://preview-${branchName}.berent.ai`;
          
          github.rest.issues.createComment({
            issue_number: prNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🚀 **Preview Deployment bereit!**\n\n📋 **Branch:** \`${branchName}\`\n🔗 **Preview URL:** ${previewUrl}\n\n✅ Deine Änderungen sind jetzt unter der Preview-URL verfügbar.`
          }); 